#
#  This file is part of SplashSync Project.
#
#  Copyright (C) 2015-2020 Splash Sync  <www.splashsync.com>
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
#  For the full copyright and license information, please view the LICENSE
#  file that was distributed with this source code.
#

language: python
os: linux
dist: xenial
python:
  - "3.6"     # current default Python on Travis CI

services:
  - docker    # Require Docker to run Splash Php Toolkit

cache:
  pip: ~
  directories:
    - docker_images

before_install:
  # Restore Docker Images from Cache
  #- docker load -i docker_images/images.tar || true

install:
  # Load SplashPy Module
  - git clone --depth=1 https://github.com/SplashSync/PyCore.git ../SplashSync-Py-Core
  - chmod 7777 -Rf ../SplashSync-Py-Core
  # Build Docker Compose
  - docker network create splashsync --attachable
  - docker-compose up -d
#  - docker-compose up

# command to run tests
script:
  # Run Splash Unit tests from Splash Toolkit
#  - bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' 172.120.0.99:8069)" != "303" ]]; do echo "Wait for Odoo..."; docker-compose logs  --tail="25" odoo; sleep 10; done'
  - docker-compose exec toolkit bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' odoo:8069)" != "200" ]]; do echo "Wait for Odoo..."; sleep 10; done'
#  - sleep 60
  - docker-compose logs odoo
  - docker-compose exec toolkit php vendor/bin/phpunit -c phpunit.xml.dist

after_failure:
  - docker-compose exec toolkit curl -s -o /dev/null -w ''%{http_code}'' odoo:8069
  - docker-compose exec toolkit curl -s -o /dev/null -w ''%{http_code}'' 172.120.0.99:8069
  - docker-compose exec toolkit curl -s -o /dev/null -w ''%{http_code}'' latest.odoo.local:8069


after_script:
  - docker-compose stop
  - docker-compose logs odoo
  -
before_cache:
  # Store Docker Images in Cache
  #- docker save -o docker_images/images.tar $(docker images -a -q)